### ISSUE TITLE
Multiple kernel trees lead to build failure

### ISSUE THREAD

**Issue by Icenowy** [GloDroid/glodroid_forks#2]
`build/make/core/base_rules.mk:325: error: kernel/icenowy/drivers/staging/greybus/tools: MODULE.TARGET.EXECUTABLES.gb_loopback_test already defined by kernel/glodroid/drivers/staging/greybus/tools.`

**Comment by rsglobal** [comment]
Are you fine with 5.6-rc kernel for the pinetab/phone?

**Comment by Icenowy** [comment]
Yes.
________________________________

**Comment by rsglobal** [comment]
Then lets go with common kernel.
