### ISSUE TITLE
On PinePhone hwcomposer is quite broken

### ISSUE THREAD

**Issue by Icenowy** [GloDroid/glodroid_forks#5]
Graphics glitches happen, and when a pop up window shows, the background may tune black.

Enabling "Disable HW overlays" in dev options fixes these issues.

**Comment by rsglobal** [comment]
Setting of hwc.drm.exclude_non_hwfb_imports=1 property should disable hw composition permanently.

I also experiencing this issues. Also kernel patch https://github.com/glodroid/glodroid_forks/commit/e59267f257a31110d6f814051dd475c4171feda4 reduces FPS rate from 60 to 30. But without this commit there are a way more glitches.

**Comment by rsglobal** [comment]
Jernei suggest not to block atomic commit, instead use finish_irq to update registers.
https://lore.kernel.org/patchwork/patch/1172548/

It should fix 30fps issue, but black screen issue needs more investigation.

**Comment by Icenowy** [comment]
Should I set hwc.drm.exclude_non_hwfb_imports=1 in the project?

**Comment by rsglobal** [comment]
> Should I set hwc.drm.exclude_non_hwfb_imports=1 in the project?

In case you need something stable now - then yes.

On mali-400 - DE2.0 significantly off-loads GPU and makes UI a way smoother.

Currently I am working on 30FPS issue.

Do you have some time to investigate / fix black screen blinks?
I have some ideas where to start looking and can share my experience with drm-hwc.

**Comment by rsglobal** [comment]
I've disabled compositor and reverted kernel patch that causes FPS drop.
opi3 UI is smooth from now.

**Comment by rsglobal** [comment]
There is one more option that was added to drm_hwc recently, please try it on pinephone:

```diff
diff --git a/common/drm.rc b/common/drm.rc
index c800c1a..0fce486 100644
--- a/common/drm.rc
+++ b/common/drm.rc
@@ -11,3 +11,3 @@ on early-boot
     setprop hwc.drm.device /dev/dri/card0
     setprop gralloc.gbm.device /dev/dri/card0
-    setprop hwc.drm.exclude_non_hwfb_imports 1
+    setprop hwc.drm.scale_with_gpu 1
```

In addition to that you can provide already  scaled wallpaper image, so GPU won't scale it every time.

**Comment by rsglobal** [comment]
KMS is enabled for planes with 0 deg. rotation that does not require scaling.
Scaling is still broken. Rotation support is WIP now.
